// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAavp7nMoFBxDaTitoR0TUvP4tA1CqeBrc',
    appId: '1:871284244553:web:df354f64a79c4147ee7f98',
    messagingSenderId: '871284244553',
    projectId: 'careercoach-a969c',
    authDomain: 'careercoach-a969c.firebaseapp.com',
    databaseURL: 'https://careercoach-a969c-default-rtdb.firebaseio.com',
    storageBucket: 'careercoach-a969c.firebasestorage.app',
    measurementId: 'G-EYBWQ94RT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Ocm1b7IvA6EGvzpqK7Ix_kB4ZSe5ja8',
    appId: '1:871284244553:android:c33ec959c0b20ec7ee7f98',
    messagingSenderId: '871284244553',
    projectId: 'careercoach-a969c',
    databaseURL: 'https://careercoach-a969c-default-rtdb.firebaseio.com',
    storageBucket: 'careercoach-a969c.firebasestorage.app',
  );
}
